language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install: pip install coverage

script: nosetests --with-coverage --cover-min-percentage=100

notifications:
  email:
    on_success: never
    on_failure: always
